receivers:
    otlp:
        protocols:
            grpc:
            http:

processors:
    batch:

exporters:
    prometheus:
        endpoint: "0.0.0.0:8889" # Prometheus exporter endpoint
    otlp/2:
        endpoint: tempo:4317
        tls:
            insecure: true

service:
    pipelines:
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus]
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/2]
