FROM nginx:stable-otel@sha256:ce3fdf748adb438d286fc47b167da09334be69a1321b5366424ee3072a8b3f86

# TODO May be worth it use less priveleged user to limit the scope of access
COPY html/ /usr/share/nginx/html/


