name: 'Reusable Terragrunt Workflow'

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

      environment:
        required: true
        type: string

      region:
        required: true
        type: string

      token:
        required: false
        type: string
        default: '${{ github.token }}'


      tf_version:
        required: false
        type: string

      apply:
        required: false
        type: boolean
        default: false

      format:
        required: false
        type: boolean
        default: true

      run_output:
        required: false
        type: boolean
        default: true

      generate_artifacts:
        required: false
        type: boolean
        default: false

    secrets: #      TODO Avoid defining here what are the environments and abstract this later
      global_account_id:
        required: true

      mgmt_account_id:
        required: true

      dev_account_id:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GLOBAL_ACCOUNT_ID: ${{secrets.GLOBAL_ACCOUNT_ID}}
      MGMT_ACCOUNT_ID: ${{secrets.MGMT_ACCOUNT_ID}}
      DEV_ACCOUNT_ID: ${{secrets.DEV_ACCOUNT_ID}}
      output_json_path: 'tmp/output.json'
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
#    outputs:

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{ inputs.tf_version }}"

      - name: Set up Terragrunt
        uses: jaxxstorm/action-install-gh-release@v1.13.0
        with:
          token: '${{ inputs.token }}'
          repo: gruntwork-io/terragrunt
          asset-name: "terragrunt_linux_amd64"
          extension-matching: disable
          rename-to: terragrunt
          chmod: 0755

      - name: Authenticating to AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.TERRAFORM_IAM_ROLE}}
          aws-region: ${{ inputs.region}}

      - name: Format Terraform
        if: inputs.format
        run: "make fmt ENV=${{inputs.environment}}"

      - name: Plan Terraform
        run: "make plan ENV=${{inputs.environment}}"

      - name: Apply Terraform
        if: inputs.apply
        run: "make apply ENV=${{inputs.environment}}"

      - name: Terraform Output
        if: inputs.run_output && ! inputs.generate_artifacts
        run: "make output ENV=${{inputs.environment}}"

      - name: Terraform Output To File
        if: inputs.run_output && inputs.generate_artifacts
        run: "make output ENV=${{inputs.environment}} > ${{ env.output_json_path }}"


#      TODO Consider to create a script that transforms the terraform json output into valid values
      - name: Generate Artifacts
        if: inputs.generate_artifacts && inputs.run_output
        uses: actions/upload-artifact@v4
        with:
          name: terraform-output-artifacts
          path: ${{ env.output_json_path }}
